services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_OTLP_ENABLED: true
    ports:
      - 127.0.0.1:16686:16686
      - 127.0.0.1:4317:4317
      - 127.0.0.1:4318:4318
